const test = require('tape')

test('should not throw when authorized', (t) => {
  // TODO: write a test that fails due to the bug in
  // SafeCalculator.add()
  t.end()
})
